spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbtest?useSSL=false
    username: root
    password: 123456
  thymeleaf:
    #是关闭thymeleaf的缓存，不然在开发过程中修改页面不会立刻生效需要重启，生产可配置为true。
    cache: false
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制)
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
mybatis:
  type-aliases-package: com.jyj.seckill.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  config: classpath:config/logback-spring.xml
  #configuration:
    # 使用jdbc的getGenertaedKeys获取数据库自增主键值
  #  use-generated-keys: true
    # 使用列别名替换列名 默认：true
    # select name as title from table
  #  use-column-label: true
    # 开启驼峰命名转换：Table(create_time) -> Entity(createTime)
  #  map-underscore-to-camel-case: true